# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sr17', '0004_nutrients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_des',
            name='adjusted_protein',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='alanine',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='alcohol',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='arginine',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='ash',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='aspartic_acid',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='beta_sitosterol',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='betaine',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='caffeine',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='calcium',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='campesterol',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='carbohydrate',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='carotene_alpha',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='carotene_beta',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='cholesterol',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='choline',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='copper',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='cryptoxanthin_beta',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='cystine',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='dihydrophylloquinone',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='energy_kj',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f10d0',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f12d0',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f13d0',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f14d0',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f14d1',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f15d0',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f15d1',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f16d0',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f16d1',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f16d1c',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f16d1t',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f17d0',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f17d1',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f18d0',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f18d1',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f18d1c',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f18d1t',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f18d1tn7',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f18d2',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f18d2cla',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f18d2cn6',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f18d2i',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f18d2t',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f18d2tt',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f18d3',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f18d3cn3',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f18d3cn6',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f18d3i',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f18d4',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f20d0',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f20d1',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f20d2cn6',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f20d3',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f20d3n3',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f20d3n6',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f20d4',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f20d4n6',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f20d5',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f21d5',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f22d0',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f22d1',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f22d1c',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f22d1t',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f22d4',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f22d5',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f22d6',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f24d0',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f24d1c',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f4d0',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f6d0',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='f8d0',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='fiber',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='fluoride',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='folate',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='folate_dfe',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='folate_food',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='folic_acid',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='fructose',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='galactose',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='glucose',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='glutamic_acid',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='glycine',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='histidine',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='hydroxyproline',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='iron',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='isoleucine',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='lactose',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='leucine',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='lutein_zeaxanthin',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='lycopene',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='lysine',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='magnesium',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='maltose',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='manganese',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='menaquinone_4',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='methionine',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='monounsaturated_fatty_acids',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='niacin',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='pantothenic_acid',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='phenylalanine',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='phosphorus',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='phytosterols',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='polyunsaturated_fatty_acids',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='potassium',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='proline',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='retinol',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='riboflavin',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='saturated_fatty_acids',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='selenium',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='serine',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='sodium',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='starch',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='stigmasterol',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='sucrose',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='sugars_total',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='theobromine',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='thiamin',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='threonine',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='tocopherol_beta',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='tocopherol_delta',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='tocopherol_gamma',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='tocotrienol_alpha',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='tocotrienol_beta',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='tocotrienol_delta',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='tocotrienol_gamma',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='trans_fatty_acids',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='trans_monoenoic_fatty_acids',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='trans_polyenoic_fatty_acids',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='tryptophan',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='tyrosine',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='valine',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='vitamin_a',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='vitamin_a_rae',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='vitamin_b12',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='vitamin_b12_added',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='vitamin_b6',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='vitamin_c',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='vitamin_d',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='vitamin_d2',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='vitamin_d2_d3',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='vitamin_d3',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='vitamin_e',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='vitamin_e_added',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='vitamin_k',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='water',
        ),
        migrations.RemoveField(
            model_name='food_des',
            name='zinc',
        ),
    ]
